language: node_js
cache:
  directories:
  - vendor/bundle
  - bower_components
  - node_modules
node_js:
- 4.4.3
install: "./setup.sh"
script: npm run build
after_success: "./deploy.sh"
env:
  global:
  - GIT_NAME=Travis-CI
  - GIT_EMAIL=ciaran.lyons@gmail.com
  - GIT_DOMAIN=github.com
  - secure: Xofmqss5/3hB4XQpTthbfkoZ9mF/y6XnmcgWUrDxNMdp5ZTXPiRLqp3u8jw3cBhWzXr3v72YFxQFRxR6Xnv4qlTHVh6yJ5p+MZMxslsIlg0st8TiAQfMoz2kG6YNtQcLVkiLXCG4YTAQOHZkLI0IEES3xN5jgTRh3sdftOKe9AfHzA+3TppstCVHlrP2djz3l0G+h/LAGNRduV+aj1z1qY6Pyt7yfBfaU6DJJcrq0WPJyGle8AE8DKeOQvFCnSi5QEgTrA5Sn+4RPJ16wPC9Ee7KJIYgjBLwAx40txoan2byYPUGB3tsc2cXmxbF+3PmmLx2bqlJj02Ibu2YlYlMd2zbb7zPOUeZwFnRlMwKYCDM631YnrDrj82RnVJrvzbQBgAfe+a/XedtoZFZ8XsvXI/wkKWKqb5J6YplvoUr5FB/T7b0UphfIun33srvMKWTjNOOqrQGpMxM79xAysWFUyTI9tZWp8fG52PWxCh0hcnmELm9CDEhSltGKznuGna8lD3RgNqhxBTRYTR2YzcMcO6zpNto6RYooLS1JC9TShrOEFgIsIBhPKevvw86kK+SOtzpcoxoqZjsRrgEi5yfuPKQfazYPyzvDLNH2T6h4NMNMZYkhWy3ZOzHUCf/WEKwI4/+VgR10ZykYR2Fx5oBcnb7pmylTo5M3QMV29CFr8s=
